# Generated by Django 4.1.5 on 2023-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcount',
            name='cost_price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='costcount',
            name='selling_price',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
