# Generated by Django 4.1.5 on 2023-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_costcount_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='img',
            field=models.URLField(blank=True, default=''),
        ),
    ]
