# Generated by Django 4.1.5 on 2023-01-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_storageitem_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costcount',
            old_name='selling_price',
            new_name='selling',
        ),
    ]
