# Generated by Django 4.1.5 on 2023-01-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_selling_price_costcount_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcount',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='threshold',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
