# Generated by Django 4.1.5 on 2023-01-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_costcount_sold_count_storageitem_restock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcount',
            name='cost_price',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='costcount',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='costcount',
            name='selling',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='costcount',
            name='sold_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='restock',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='threshold',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
